my:
  name: lz_dev
  age: 25
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}
  mapProp: {key1: value1, key2: value2}
  mapProp2:
    key11: value11
    key22: value22

  iplist:
   - ip1
   - ip2
server:
  port: 8088